### ISSUE TITLE
Install form

### ISSUE THREAD

**Issue by mheguy** [KSP-CKAN/metadata-webtool#4]
I whipped up https://form.jotform.com/61407154878260 as a guide which should cover most cases.
"Install" would determine what we feed to `file` and "into the folder" would determine our `install_to` and if "GameData" is selected we allow for a subdirectory to be specified, lastly we offer a chance to filter unnecessary files.

"Add" and "remove" buttons should be presented to increase or decrease the number of install directives generated, and we should present the "Results" summary: a plain-English explanation of what we will install and where.

This implementation ignores the possibility of using other install methods such as `find` and `find_regexp` for simplicity. Strictly using `file` lets us sidestep https://github.com/KSP-CKAN/CKAN/issues/1477 at the expense of decreased future-proofing.

The restrictions to the install tools also means we are unlikely to need anything above spec `v1.2`. Since that's a very low barrier for entry I think we can safely use `v1.2` at all times until we expand the toolset to include `find`, `find_regexp`, `find_matches_files` and the like.

I would love input from my fellow @KSP-CKAN/wranglers, @dbent, and @techman83 on this subject.

**Comment by politas** [comment]
Ooh, this is an excellent idea! :+1: :+1: If we can get Spacedock to incorporate this it would be very good. Then we'd just need a relationships picker, which shouldn't be too hard, and SpaceDuck submissions would become a regular check & merge, rather than the usual completely redo it.
1. I would like to see "at the path" changed to make it clear we are referring to a location inside the zipfile, in case someone thinks they can add URLs (though that might be a good function to add someday, now that I think of it!)
2. We should capture and convert backslashes to forward slashes.
3. The Results should not include the "but will not install" phrase unless there is something to filter.
