### ISSUE TITLE
Design Idea: Read mod zip and Extract paths for selection

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/metadata-webtool#7]
This one is definitely for after things are working.

Zip file paths are another common problem. It'd be neat to be able to scan a zip for a mod and allow building install stanzas from it. [jszip](https://stuk.github.io/jszip/)

**Comment by janbrohl** [comment]
While reading paths from a zip is simple and even generating complete install directives from it ( addressing #4 ) should not be very hard in some cases, doing this in the browser can be a problem at least for big files as the zip-format does not support streaming.

Also - when analyzing archives we could also:
- check for paths that are not portable - most from https://www.gnu.org/software/tar/manual/tar.html#SEC140 applies to zips, too
- look for included dependencies and populate that field
- look for KSP-AVC version files to populate $vref and the fields not auto-filled by netkan on $vref (versions are interesting for dependencies, too)
  - offer to normalize path layout of the archive according to install directives
  - offer to generate a new archive with dependencies included (for mod authors who want to offer standalone downloads)

**Comment by mheguy** [comment]
Could we restrict the functionality to mods that are < 20 MB in size or something? Because I totally agree some mods are gargantuan and would choke users if they have to wait for the download to finish.

> look for included dependencies and populate that field

That sounds cool but also really tricky. A lot of popular mods (especially those that have a lot of mods depending on them) have their core elements broken in their own mod. `Firespitter` for example has the .dll in `FirespitterCore` and the resource.cfg in `FirespitterResourcesConfig`. So essentially we need to not only check for folder names but the precise contents of said folders.

Worth tossing a ref to https://github.com/KSP-CKAN/CKAN/issues/1607 since that's a major component of what that does.

**Comment by janbrohl** [comment]
From an UI standpoint it is much easier to only allow uploads from the user's computer to the form - no progress bars and stuff - also as the data don't have to travel the net it is fast.

**Comment by janbrohl** [comment]
Implemented flawed autocomplete (see PR) with jszip. It works with 500MB zip in Firefox 46 without visible lag.
